### ISSUE TITLE
Exception when using temp

### ISSUE THREAD

**Issue by peiqianggao** [seza443/Wox.Plugin.SystemTemp#2]
2017-06-20 11:23:50.7368|ERROR|PluginManager.QueryForPlugin|-------------------------- Begin exception --------------------------
2017-06-20 11:23:50.7368|ERROR|PluginManager.QueryForPlugin|Exception for plugin <Core Temperature> when query <temp>
2017-06-20 11:23:50.7368|ERROR|PluginManager.QueryForPlugin|Exception fulle name:
 <System.Management.ManagementException>
2017-06-20 11:23:50.7368|ERROR|PluginManager.QueryForPlugin|Exception message:
 <Access denied >
2017-06-20 11:23:50.7368|ERROR|PluginManager.QueryForPlugin|Exception stack trace:
 <   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Wox.Plugin.SystemTemp.Temperature.get_Temperatures() in D:\tangu\Documents\Projects\Wox\Wox.Plugin.SystemTemp\Wox.Plugin.SystemTemp\SystemTemp.cs:line 50
   at Wox.Plugin.SystemTemp.SystemTemp.Query(Query query) in D:\tangu\Documents\Projects\Wox\Wox.Plugin.SystemTemp\Wox.Plugin.SystemTemp\SystemTemp.cs:line 23
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 178
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 0>
2017-06-20 11:23:50.7428|ERROR|PluginManager.QueryForPlugin|Exception source:
 <System.Management>
2017-06-20 11:23:50.7428|ERROR|PluginManager.QueryForPlugin|Exception target site:
 <Void ThrowWithExtendedInfo(System.Management.ManagementStatus)>
2017-06-20 11:23:50.7428|ERROR|PluginManager.QueryForPlugin|Exception HResult:
 <-2146233087>
2017-06-20 11:23:50.7428|ERROR|PluginManager.QueryForPlugin|-------------------------- End exception --------------------------

**Comment by seza443** [comment]
Hi, thanks for reporting this issue.

1. This error doesn't happen on my local machine. Do you run Wox with administrator privileges?
2. Actually this plugin had never worked properly so I guess I should just remove it from Wox for now and maybe improve it when I'll have some time

**Comment by peiqianggao** [comment]
Thanks for your reply and what you've done.
